apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hello-world
data:
  default.conf: |
    server {
      listen 443 ssl;

      ssl_certificate     /etc/nginx/tls/tls.crt;
      ssl_certificate_key /etc/nginx/tls/tls.key;

      # Enable mTLS
      ssl_client_certificate /etc/nginx/tls/ca.crt;
      ssl_verify_client on;

      location / {
        default_type text/plain;
        return 200 "Hello from mTLS-secured NGINX!\n";
      }
    }
