apiVersion: v1
kind: Secret
metadata:
  name: hello-server-tls
  namespace: hello-world
type: kubernetes.io/tls
data:
  tls.crt: {{Sbase64 -w0 certs/output/server.crt}}
  tls.key: {{Sbase64 -w0 certs/output/server.key}}
